### ISSUE TITLE
Parameters passed while creating a UDF are being ignored.

### ISSUE THREAD

**Issue by americast** [georgia-tech-db/evadb#1003]
### Search before asking

- [X] I have searched the EvaDB [issues](https://github.com/georgia-tech-db/eva/issues) and found no similar bug report.

### Bug

While creating a custom UDF, the parameters passed along with it are being ignored.

For instance, if `CREATE UDF <name> IMPL <path> '<option1>' '<param1>';` is executed, the EvaDB does not assign `option1` as `param1`, but goes with the default value.

Thanks!

### Environment

- EvADB: staging branch

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by gaurav274** [comment]
@xzdandy @americast Is it done?

**Comment by xzdandy** [comment]
I do not think it is needed anymore. We can close.
