### ISSUE TITLE
MySQL Integration Bugs

### ISSUE THREAD

**Issue by gaurav274** [georgia-tech-db/evadb#1020]
### Search before asking

- [X] I have searched the EvaDB [issues](https://github.com/georgia-tech-db/eva/issues) and found no similar bug report.

### Bug

@rohithmulumudy - A few things need to be improved:

- `get_columns` has to be updated - It should have the following two columns: name and dtype. The dtype should be a Python dtype and will default to str.
- The init should have self.connection = None

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by jiashenC** [comment]
https://github.com/georgia-tech-db/evadb/pull/1019
