### ISSUE TITLE
Docs: Model training documentation has no links on how to create database, load data etc. 

### ISSUE THREAD

**Issue by gaurav274** [georgia-tech-db/evadb#1069]
1. Add links to create database command.
2. No explanation of `TIME_LIMIT `
3. Need a better explanation for `PREDICT`

**Comment by xzdandy** [comment]
The AI engine page is intended only to show the documentation for the AI engine. We will add a table to illustrate all configurable parameters.

For loading data, we will add a usecase documentation page to cover that.

**Comment by xzdandy** [comment]
Merge into #999
