### ISSUE TITLE
Model training raises error with `ludwig`

### ISSUE THREAD

**Issue by gaurav274** [georgia-tech-db/evadb#1071]
### Search before asking

- [X] I have searched the EvaDB [issues](https://github.com/georgia-tech-db/eva/issues) and found no similar bug report.

### Bug

The keyword `Ludwig` should not be case-sensitive. 

Does not work when passed `ludwig`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by hershd23** [comment]
Hey, can I take this?

**Comment by hershd23** [comment]
This is solved.
