### ISSUE TITLE
Improve the univariate statsforecast function in EvaDB

### ISSUE THREAD

**Issue by xzdandy** [georgia-tech-db/evadb#1081]
### Search before asking

- [X] I have searched the EvaDB [issues](https://github.com/georgia-tech-db/eva/issues) and found no similar feature requests.

### Description

* [x] The univariate statsforecast function train and predicts on the exact same input relation, so there is no need for a separate training procedure. Currently `SELECT Forecast(12) FROM AirData;` does not make sense.
* [ ] The timeseries column is not properly handled. statsforecast has a required format for the timeseries column. https://nixtla.github.io/statsforecast/docs/getting-started/getting_started_short.html
* [x] The univariate statsforecast expects a fixed schema for the input dataframe. Renaming the column is not handled properly now. 
* [x] Update documentation with all available parameters. 

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by americast** [comment]
> The univariate statsforecast function train and predicts on the exact same input relation, so there is no need for a separate training procedure. Currently SELECT Forecast(12) FROM AirData; does not make sense.

I believe we can simply do `SELECT Forecast(12);`. The `FROM` part is a little redundant, but I am not sure if that is in line with SQL syntax.

@xzdandy I'll take care of `2`, you can assign it to me. Thanks!

**Comment by xzdandy** [comment]
> > The univariate statsforecast function train and predicts on the exact same input relation, so there is no need for a separate training procedure. Currently SELECT Forecast(12) FROM AirData; does not make sense.
> 
> I believe we can simply do `SELECT Forecast(12);`. The `FROM` part is a little redundant, but I am not sure if that is in line with SQL syntax.
> 
> @xzdandy I'll take care of `2`, you can assign it to me. Thanks!

Thanks @americast! `SELECT Forecast(12)` the syntax is not supported. We can add that. I will handle  `3` first, which does not allow me to doing forecast on tables with customized column names.  

For time data type, it can be tricky. For example, I am using [House Property Sales Time Series](https://www.kaggle.com/datasets/htagholdings/property-sales?resource=download) data set, where the saledate column is `30/09/2007`, which is not the default panda data type format. We need to support some kind of data type and conversion here. Any idea you have.

**Comment by americast** [comment]
>I will handle 3 first, which does not allow me to doing forecast on tables with customized column names.

@xzdandy I had added some support for customized column names in #969 . It's handled by the `id` and `time` variables. Are they not working for you?

**Comment by xzdandy** [comment]
> > I will handle 3 first, which does not allow me to doing forecast on tables with customized column names.
> 
> @xzdandy I had added some support for customized column names in #969 . It's handled by the `id` and `time` variables. Are they not working for you?

It is not working. 1) the change is to the aggregated_batch instead of data. This can be easily fixed. 2) The output object of the UDF is not correctly binded. So in projection, we are looking for a non-existent column.

**Comment by xzdandy** [comment]
From the warning message, `/home/zxu330/eva/evadb-venv-test/lib/python3.10/site-packages/statsforecast/core.py:691: UserWarning: Parsing dates in %d/%m/%Y format when dayfir
st=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.` It seems we can specify a time format to parsing. We can explore this option.
