### ISSUE TITLE
Drop table not working

### ISSUE THREAD

**Issue by americast** [georgia-tech-db/evadb#1083]
### Search before asking

- [X] I have searched the EvaDB [issues](https://github.com/georgia-tech-db/eva/issues) and found no similar bug report.

### Bug

Dropping table fails.

```python
import evadb
cursor = evadb.connect().cursor()

cursor.query("CREATE TABLE AirData3 (\
    unique_id TEXT(30),\
    ds TEXT(30),\
    y INTEGER);").execute()

cursor.query("DROP TABLE IF EXISTS AirData3;").execute()
```

leads to this error: 
`evadb.executor.executor_utils.ExecutorError: Delete table failed for TableCatalogEntry(name='AirData3', file_url='$HOME/evadb/evadb_data/evad
b_datasets/1e6c178f4e86a1b789be8b7b941aef10', table_type=<TableType.STRUCTURED_DATA: 1>, identifier_column=None, columns=[ColumnCatalogEntry(name='_ro
w_id', type=<ColumnType.INTEGER: 2>, is_nullable=False, array_type=None, array_dimensions=(), table_id=3, table_name='AirData3', row_id=9, dep_caches=
[]), ColumnCatalogEntry(name='unique_id', type=<ColumnType.TEXT: 4>, is_nullable=True, array_type=None, array_dimensions=(30,), table_id=3, table_name
='AirData3', row_id=10, dep_caches=[]), ColumnCatalogEntry(name='ds', type=<ColumnType.TEXT: 4>, is_nullable=True, array_type=None, array_dimensions=(
30,), table_id=3, table_name='AirData3', row_id=11, dep_caches=[]), ColumnCatalogEntry(name='y', type=<ColumnType.INTEGER: 2>, is_nullable=True, array
_type=None, array_dimensions=(), table_id=3, table_name='AirData3', row_id=12, dep_caches=[])], row_id=3) with error (sqlite3.OperationalError) no suc
h column: index_catalog.function`

### Environment

- EvaDB: v0.3.4 (or staging)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by xzdandy** [comment]
Can not reproduce the problem. Can you confirm the EvaDB version? Maybe try removing the `evadb_data` in case it contains the old version's data.

**Comment by americast** [comment]
That helped, thanks! :smile:
