### ISSUE TITLE
Circle ci unit tests are flaky now

### ISSUE THREAD

**Issue by xzdandy** [georgia-tech-db/evadb#1098]
### Search before asking

- [X] I have searched the EvaDB [issues](https://github.com/georgia-tech-db/eva/issues) and found no similar bug report.

### Bug

[Examples](https://app.circleci.com/pipelines/github/georgia-tech-db/evadb/5316/workflows/81ba6d46-747d-4f21-b403-a9527f24e742/jobs/38223)

Usually, we rerun it (rerun workflow from failed) from the circle ci page. The error will disappear. 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by gaurav274** [comment]
I believe it is a timeout issue. @jiashenC

**Comment by jiashenC** [comment]
Attach for later reference https://bugs.python.org/issue29130

**Comment by jiashenC** [comment]
https://github.com/georgia-tech-db/evadb/pull/1122

**Comment by jiashenC** [comment]
Close as https://github.com/georgia-tech-db/evadb/pull/1122 is merged as a fix for now.
