### ISSUE TITLE
Merlion support for forecasting

### ISSUE THREAD

**Issue by americast** [georgia-tech-db/evadb#1099]
### Search before asking

- [X] I have searched the EvaDB [issues](https://github.com/georgia-tech-db/eva/issues) and found no similar feature requests.

### Description

Currently, time series forecasting uses the [`statsforecast` ](https://github.com/Nixtla/statsforecast) package. However, it is limited to statistical forecasting methods only. [`Merlion`](https://github.com/salesforce/Merlion), however, supports both statistical forecasting and DL-based forecasting methods. Moreover, it also supports multivariate forecasting. Hence, it would be great to have support for `Merlion` library for forecasting.

### Use case

Support for `Merlion` could be useful for extending forecasting to support multivariate and DL-based forecasting.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by xzdandy** [comment]
Do we still plan to add Merlion support for forecasting?

**Comment by americast** [comment]
Since Merlion requires Spark, as of now, we would not like to add Merlion support.
