### ISSUE TITLE
pip install the staging version of EvaDB in tutorials/15-AI-powered-join

### ISSUE THREAD

**Issue by xzdandy** [georgia-tech-db/evadb#1104]
### Search before asking

- [X] I have searched the EvaDB [issues](https://github.com/georgia-tech-db/eva/issues) and found no similar bug report.

### Bug

In https://github.com/georgia-tech-db/evadb/blob/staging/tutorials/15-AI-powered-join.ipynb, we have `%pip install git+https://github.com/georgia-tech-db/evadb.git@staging`, which does not install the stable version of EvaDB. 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by jiashenC** [comment]
I will focus on fixing issues in doc and notebooks today.

**Comment by jiashenC** [comment]
This has been fixed.
