### ISSUE TITLE
No `AS` requirements for nested `SELECT` queries

### ISSUE THREAD

**Issue by xzdandy** [georgia-tech-db/evadb#1129]
### Search before asking

- [X] I have searched the EvaDB [issues](https://github.com/georgia-tech-db/eva/issues) and found no similar feature requests.

### Description

Right now for nested SELECT queries, the rename `AS` is required in the query. For example,

```
SELECT price FROM (SELECT price FROM home_sales) AS T;
```

The following query will not work:

```
SELECT price FROM (SELECT price FROM home_sales);
```

We'd like to add the support for nested SELECT queries without AS to simplify the queries that user wrote. 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by gaurav274** [comment]
https://www.postgresql.org/docs/7.3/queries-table-expressions.html#QUERIES-SUBQUERIES - PostgreSQL has a similar behavior. We can skip it.

**Comment by xzdandy** [comment]
Sounds good. Let's keep it consistent iwth PostgreSQL.
