### ISSUE TITLE
Configuration Manager Redesign 

### ISSUE THREAD

**Issue by xzdandy** [georgia-tech-db/evadb#1140]
### Search before asking

- [X] I have searched the EvaDB [issues](https://github.com/georgia-tech-db/eva/issues) and found no similar feature requests.

### Description

We'd like to move away from the yml file, and use a catalog to store all EvaDB's configuration (e.g., ray enabled or not). We'd like also to introduce a new SQL command to adjust those configurations. 

- [x] Introduce `SET` commands to change the configuration as needed. #1180
- [ ] Switch the configuration into a persistent SQL table.
- [ ] Introduce a `GET` -like commands to get the current configuration value. 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by hershd23** [comment]
I have captured the main ideas in this doc https://docs.google.com/document/d/1tnePjSJqj9zuhHc8Cu-220tjh0Sv0uOlSUYWx-L6wjA/edit?usp=sharing

Right now #1180 takes care of setting configuration parameters. Will have the `get` calls for configs and configuration manager persistance in separate PRs.

Wanted to get your opinion on the `get` calls for config params.
Duck DB does something like https://duckdb.org/docs/sql/configuration.html

```SELECT current_setting('access_mode');```

And Postgres does it with https://www.postgresql.org/docs/current/sql-show.html

```Show <name>```

Which approach should we take, any ideas? @xzdandy @gaurav274 @jiashenC @jarulraj

**Comment by xzdandy** [comment]
Thanks Hersh for the design doc. Provided feedback there. I like the `Show` better, which is consistent with the current `SHOW TABLES` and `SHOW FUNCTOINS` now, though we will need some design like `SHOW SETTINGS` to differentiate from TABLE and FUNCTIONS, so the syntax will not be identical to Postgres.  

Wrapping up #1180 for `SET` and having other changes in following PRs sounds good to me.
