### ISSUE TITLE
Load PDF bug

### ISSUE THREAD

**Issue by jiashenC** [georgia-tech-db/evadb#1156]
### Search before asking

- [X] I have searched the EvaDB [issues](https://github.com/georgia-tech-db/eva/issues) and found no similar bug report.

### Bug

Load PDF command uses lower case does not trigger parser error but triggers executor exception.

```python
cur = evadb.connect().cursor()
cur.query("load pdf 'omscentral.pdf' into testpdf").df()
```

Error output from the exception.

> 09-17-2023 23:16:48 ERROR [plan_executor:plan_executor.py:execute_plan:0182] cannot access local variable 'executor' where it is not associated with a value
> Traceback (most recent call last):
>   File "/Users/jiashenc/Workspace/eva/evadb/executor/plan_executor.py", line 178, in execute_plan
>     yield from output
>   File "/Users/jiashenc/Workspace/eva/evadb/executor/load_executor.py", line 44, in exec
>     for batch in executor.exec():
>                  ^^^^^^^^
> UnboundLocalError: cannot access local variable 'executor' where it is not associated with a value
> Traceback (most recent call last):
>   File "/Users/jiashenc/Workspace/eva/evadb/executor/plan_executor.py", line 178, in execute_plan
>     yield from output
>   File "/Users/jiashenc/Workspace/eva/evadb/executor/load_executor.py", line 44, in exec
>     for batch in executor.exec():
>                  ^^^^^^^^
> UnboundLocalError: cannot access local variable 'executor' where it is not associated with a value
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/jiashenc/Workspace/eva/evadb/interfaces/relational/relation.py", line 110, in df
>     batch = self.execute()
>             ^^^^^^^^^^^^^^
>   File "/Users/jiashenc/Workspace/eva/evadb/interfaces/relational/relation.py", line 120, in execute
>     result = execute_statement(self._evadb, self._query_node.copy())
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/jiashenc/Workspace/eva/evadb/server/command_handler.py", line 53, in execute_statement
>     batch_list = list(output)
>                  ^^^^^^^^^^^^
>   File "/Users/jiashenc/Workspace/eva/evadb/executor/plan_executor.py", line 183, in execute_plan
>     raise ExecutorError(e)
> evadb.executor.executor_utils.ExecutorError: cannot access local variable 'executor' where it is not associated with a value

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by jiashenC** [comment]
@xzdandy @gaurav274 Currently, other commands are case-insensitive, but those document types are still case-sensitive. Should we also make those case-insensitive?

Regardless, we should provide better error msg instead of failing inside the executor.

**Comment by xzdandy** [comment]
I agree. We shall make it consistent. We can use ‘string_comparison_case_insensitive’ for string comparisons.
