### ISSUE TITLE
`COUNT(*)` does not work as expected

### ISSUE THREAD

**Issue by pchunduri6** [georgia-tech-db/evadb#1170]
### Search before asking

- [X] I have searched the EvaDB [issues](https://github.com/georgia-tech-db/eva/issues) and found no similar bug report.

### Bug

COUNT(*) throws an `invalid column id` error.
![image](https://github.com/georgia-tech-db/evadb/assets/43007047/38d5961f-79a6-4550-89ee-a5f87d9a4525)

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by jkim3663** [comment]
Hello, I am planning to take this issue if no one is currently working on it for 4420 evadb project. Thanks!

**Comment by pchunduri6** [comment]
> Hello, I am planning to take this issue if no one is currently working on it for 4420 evadb project. Thanks!

Sounds good, thanks!

**Comment by pchunduri6** [comment]
@jkim3663 sounds good, thanks!

**Comment by jkim3663** [comment]
@xzdandy  @pchunduri6  Hey everyone, I just wanted to note that `COUNT(*) `was creating BindingError even without the GROUP BY. E.g., `"SELECT COUNT(*) FROM MyPDFs;"` was also causing error, but now it is resolved. I'll update my PR's name to be more generic to also reflect this fix.
