### ISSUE TITLE
evadb.executor.executor_utils.ExecutorError: could not convert string to float: '2022-09-19'

### ISSUE THREAD

**Issue by haoranx3** [georgia-tech-db/evadb#1184]
### Search before asking

- [X] I have searched the EvaDB [issues](https://github.com/georgia-tech-db/eva/issues) and found no similar bug report.

### Bug

Running into error `could not convert string to float: '2022-09-19'` when creating a forecast function as follow:
```
cursor.query("""
  CREATE FUNCTION IF NOT EXISTS StockPriceForecast FROM
    (
      SELECT date, open, close, high, low, volume
      FROM postgres_data.historical_stock_price
    )
  TYPE Forecasting
  PREDICT 'high'
  TIME 'date'
  FREQUENCY 'W'
""").df()
```

Table schema: 
```
CREATE TABLE IF NOT EXISTS historical_stock_price (date VARCHAR(64), open decimal, close decimal, high decimal, low decimal, volume INT)
```

Example data set:

Date | Open | High | Low | Close | Volume
-- | -- | -- | -- | -- | --
2022-09-20 | 242.07000732421900 | 243.50999450683600 | 239.63999938964800 | 242.4499969482420 | 26660300
2022-09-21 | 244.27000427246100 | 247.66000366210900 | 238.89999389648400 | 238.9499969482420 | 28625600

### Environment

- evaDB: 0.3.4
- Python: 3.11
- os: Mac

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by xzdandy** [comment]
Hi @haoranx3, could you try installing the latest EvaDB? I can not reproduce this error on EvaDB v0.3.6.  Notice, you need the following query on the latest EvaDB. 
```
CREATE FUNCTION IF NOT EXISTS StockPriceForecast FROM
    (
      SELECT date, high
      FROM postgres_data.historical_stock_price
    )
  TYPE Forecasting
  PREDICT 'high'
  TIME 'date'
  FREQUENCY 'W';
```

**Comment by haoranx3** [comment]
Thank you! upgrading evadb solves the issue
