### ISSUE TITLE
Skip pinecone test if pinecone is not installed

### ISSUE THREAD

**Issue by jiashenC** [georgia-tech-db/evadb#1188]
### Search before asking

- [X] I have searched the EvaDB [issues](https://github.com/georgia-tech-db/eva/issues) and found no similar bug report.

### Bug

The integration test fails if pinecone is not installed.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Chitti-Ankith** [comment]
Should be fixed with this https://github.com/georgia-tech-db/evadb/pull/1192
