### ISSUE TITLE
`test/third_party_tests` are not running on staging branch

### ISSUE THREAD

**Issue by xzdandy** [georgia-tech-db/evadb#1251]
### Search before asking

- [X] I have searched the EvaDB [issues](https://github.com/georgia-tech-db/eva/issues) and found no similar bug report.

### Bug

Currently, we have Mysql and PostgreSQL setup on the staging branch and their third_party_tests are running on the staging branch.

However, other tests (e.g., test/third_party_tests/test_github_datasource.py, test/third_party_tests/test_native_similarity_index.py) seem to be not running on the staging now. Some of them do not need special set up, and can run with long integration tests. 

@jiashenC which is the best way to handle this? Shall we move those tests that do not need special setup out of the third_party_tests or add a special mark to tests in third_party_tests that need special setup and include the directory in the long integration.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by jiashenC** [comment]
I see. Does `test/third_party_tests/test_github_datasource.py` require special setup? If not, we can move them out. The native similarity search test needs a special setup that Postgres's vector extension needs to be enabled.

**Comment by xzdandy** [comment]
Get it. No it does not require special setup. I will move it outside `third_party_tests`. Does the native similarity search test run any where now? I think the postgres third party test also does not run the test.

**Comment by jiashenC** [comment]
Right, I doubt we can install pgvector extension for the already built docker. We probably need to setup a completely new job with a different docker image. Or, we can work on the hosted postgres issue.
