### ISSUE TITLE
Need documentation page for the new set and show config statement

### ISSUE THREAD

**Issue by xzdandy** [georgia-tech-db/evadb#1312]
### Search before asking

- [X] I have searched the EvaDB [issues](https://github.com/georgia-tech-db/eva/issues) and found no similar feature requests.

### Description

We need documentation for the following:
1. The new SET statement
2. The SHOW statement 
3. All the available configurable options. 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by hershd23** [comment]
Yes this makes a lot of sense, will get on it
