### ISSUE TITLE
Notify Users about Invalid Forward Headers

### ISSUE THREAD

**Issue by Jjx003** [georgia-tech-db/evadb#1329]
### Search before asking

- [X] I have searched the EvaDB [issues](https://github.com/georgia-tech-db/eva/issues) and found no similar feature requests.

### Description

As many issues have pointed out earlier (#1315, #1217, #1206, #1150), the forward header causes a lot of issues for users. 
In this particular request, I am asking for a mechanism to detect faulty forward headers so that users can fix the problems quickly and not have to dig into all the wrong areas of code. 

I think some ideas for requirements should be:
1. Notify users if the signature is missing. Right now, the error says "Cannot infer io signature from the decorator..."
2. Notify users if the signature is malformed (e.g. missing column names, types, or shapes)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by hershd23** [comment]
Taking this issue
