### ISSUE TITLE
Add more cv model features

### ISSUE THREAD

**Issue by hgao327** [georgia-tech-db/evadb#1332]
### Search before asking

- [X] I have searched the EvaDB [issues](https://github.com/georgia-tech-db/eva/issues) and found no similar feature requests.

### Description

We need more features for computer vision models to handle additional image processing or generation requests:

- [ ] `generateSceneGraph`: Extracting key information from a PDF document to generate scene graphs based on the document's content.

- [ ] `enhanceLowLightImages`: Image enhancement functions capable of increasing the brightness of images taken in low-light conditions.

- [ ] `superResolution`: Video/image super-resolution to enhance the model's resolution, providing a better visual experience.

### Use case

Call the functions directly through EvaDB

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by jarulraj** [comment]
This is probably not relevant any more.
