### ISSUE TITLE
Can EvaDB execute a query plan in a multi-thread environment?

### ISSUE THREAD

**Issue by onefanwu** [georgia-tech-db/evadb#1341]
### Search before asking

- [X] I have searched the EvaDB [issues](https://github.com/georgia-tech-db/eva/issues) and found no similar questions.

### Question

Hello, EvaDB team.
Can EvaDB execute a query plan in a multi-thread environment? If so, does the EvaDB query optimizer take parallel scenarios into account?

Best regards,
Yifan Wu

**Comment by jarulraj** [comment]
Hi @onefanwu. Yes, EvaDB uses Ray to run queries over multiple CPUs/GPUs if that is what you meant by a multi-threaded environment. 

However, EvaDB currently processes only one query at a time. So, it does not support concurrent queries.

**Comment by onefanwu** [comment]
Thank you for your detailed response. It has answered my questions satisfactorily. I appreciate your time and effort.

Best regards,
Yifan Wu
