### ISSUE TITLE
Explain Command output looks ugly on command line

### ISSUE THREAD

**Issue by gaurav274** [georgia-tech-db/evadb#475]
Add logic to control the formatting of the response message. Using the pandas dataframe for the explain command does not work well.

**Comment by gaurav274** [comment]
@xzdandy

**Comment by xzdandy** [comment]
Given we have switched to `PickleSerializer`, I think we can simply return other types (e.g., string). We need to fix type hint (return type) though.

**Comment by xzdandy** [comment]
The Explain command looks good now. I will close this issue. Please reopen if there are queries that the explain does not work as expected.
