### ISSUE TITLE
Improve end-to-end similarity search pipeline. 

### ISSUE THREAD

**Issue by jiashenC** [georgia-tech-db/evadb#665]
* Image loading (detailed issues are mentioned in #658).
* Similarity search engine.
  * Adapts index creation implementation to different storage engines.
  * Index scan terminate gracefully when `LIMIT n` requests more numbers than index actually has.
* Similarity search syntax.
  * Currently, the left clause in `Similarity(left, right)` only works with `Open`, I think we can improve this. 
* Secondary data
  * E.g., If the input to feature extractor is data generated from image, especially multiple data from single image, we need to keep a table to store those. One problem I saw is if we do not keep the original image in the new table, then we need to scan both tables. Otherwise, we store a lot of duplicate data in the new table. 
  * Disk full error from sqlalchemy.

**Comment by xzdandy** [comment]
Is this still in picture?
