### ISSUE TITLE
Improve CREATE TABLE query for better usability 

### ISSUE THREAD

**Issue by xzdandy** [georgia-tech-db/evadb#739]
### Search before asking

- [X] I have searched the EVA DB [issues](https://github.com/georgia-tech-db/eva/issues) and found no similar feature requests.

### Description

We'd like introduce a `CREATE TABLE` query to support common modifications (e.g., blur, flip, annotate) on a video/image table. The plan is as follows:
- [x] Add common modification UDFs from #732 
- [x] Simplify the query so that user does not need to provide a column name list. 
- [x] Rename current `CREATE MATERIALIZED VIEW` to `CREATE TABLE`
- [ ] Summarize and fix `SELECT` queries that are currently not supported with `CREATE TABLE` 
- [ ] ~~Support writing numpy array as video or image in _StorageEngine_. Reuse the implementation from #732~~ 
- [ ] ~~Integrating the new _StorageEngine_ with the `CREATE TABLE` executor~~

### Use case

We will be able to support following queries after accomplishing this feature:
- Q1: `CREATE TABLE BlurredVideo AS SELECT GaussianBlur(data) FROM Video;`
- Q2: `SELECT UDF1(data) FROM BlurredVideo;`
- Q3: `SELECT UDF2(data) FROM BlurredVideo;`
- Q4: `CREATE TABLE AnnotatedVideo AS SELECT Annotate(data, Yolo(data).bboxes) FROM Video;`
- Q5: `CREATE TABLE Video AS SELECT GaussianBlur(data) FROM Video;`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by xzdandy** [comment]
We have serialization support in sqlite_storage_engine.py. https://github.com/georgia-tech-db/eva/blob/c526f78ae25d7d54e7661fd0af0d16e062d1fba6/eva/storage/sqlite_storage_engine.py#L51

So the step `Support writing numpy array as video or image in StorageEngine` and `Integrating the new StorageEngine with the CREATE TABLE executor` become optional. We will use the serialization support in sqlite_storage_engine.py for now. If we meet performance issues, we will rethink the need to offer a specialized writer for video/images. 

On the other hand, @yulaicui found a few queries are not supported with the current `CREATE MATERIALIZED VIEW` (or `CREATE TABLE` after renaming). Yulai will summarize those queries with error messages, and we will prioritize and fix them.

**Comment by jarulraj** [comment]
@yulaicui This query in motif mining notebook is not working -- 

```CREATE MATERIALIZED VIEW IF NOT EXISTS 
      reddit_object_table (name, data, bboxes,labels)
      AS SELECT name, data, bboxes, labels FROM reddit_dataset
      JOIN LATERAL UNNEST(Yolo(data)) AS Obj(labels, bboxes, scores)"""
```

**Comment by xzdandy** [comment]
I think we are not support renaming in `CREATE TABLE ` now. The following should work:
```
CREATE TABLE reddit_object_table AS 
  SELECT 
    name, data, bboxes, labels 
  FROM reddit_dataset
    JOIN LATERAL UNNEST(Yolo(data)) AS Obj(labels, bboxes, scores);
```

**Comment by xzdandy** [comment]
This has been completed.
