### ISSUE TITLE
evadb api create_vector_index not working

### ISSUE THREAD

**Issue by affan00733** [georgia-tech-db/evadb#901]
### Search before asking

- [X] I have searched the EvaDB [issues](https://github.com/georgia-tech-db/eva/issues) and found no similar bug report.

### Bug

When I tried to create a vector index by using the a udf of sentence transformer extractor and table of csv data , error has been thrown

Code : 
`cursor.create_vector_index(
        "faiss_index",
        table_name="MyCSV",
        expr="embedding(data)",
        using="QDRANT"
    ).exeute()`

![image](https://github.com/georgia-tech-db/eva/assets/42251896/bf221b9f-6177-469c-ae4b-997b9193f9e9)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by jiashenC** [comment]
Create index executor currently directly uses the storage engine API https://github.com/georgia-tech-db/eva/blob/70ada357ba2cbb05966ab25bab73a0e9e1495713/evadb/executor/create_index_executor.py#L74, while different storage engines have different parameters, etc. Similar errors have occurred previously as well when we introduce new storage engine APIs. Maybe need a better approach here.

**Comment by affan00733** [comment]
> Create index executor currently directly uses the storage engine API
> 
> https://github.com/georgia-tech-db/eva/blob/70ada357ba2cbb05966ab25bab73a0e9e1495713/evadb/executor/create_index_executor.py#L74
> 
> , while different storage engines have different parameters, etc. Similar errors have occurred previously as well when we introduce new storage engine APIs. Maybe need a better approach here.

https://github.com/georgia-tech-db/eva/blob/70ada357ba2cbb05966ab25bab73a0e9e1495713/evadb/storage/document_storage_engine.py#L29

@jiashenC yes i also thought so and as you can see in the DocumentStorageEngine `chung_params` is required but other storage engines it is not being  required and in the case only load document is throwing the error

**Comment by xzdandy** [comment]
Our focus has been shifted to SQL support. Close this issue for now.
