### ISSUE TITLE
Eva Decord Runtime Failure

### ISSUE THREAD

**Issue by AmritK10** [georgia-tech-db/evadb#917]
### Search before asking

- [X] I have searched the EvaDB [issues](https://github.com/georgia-tech-db/eva/issues) and found no similar bug report.

### Bug

eva-decord (0.6.1) fails during runtime with the following error:

`Failed to import transformers.pipelines because of the following error (look up to see its traceback):
dlopen(/Users/amritkhera/Desktop/youtube_video_qa/venv/lib/python3.9/site-packages/decord/libdecord.dylib, 10): Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
  Referenced from: /Users/amritkhera/Desktop/youtube_video_qa/venv/lib/python3.9/site-packages/decord/libdecord.dylib (which was built for Mac OS X 12.6)
  Expected in: /usr/lib/libc++.1.dylib`
  
The error seems to be related to the Mac OS version (10.15+) as eva-decord seems to be supporting 12+
The exact environment details including OS is mentioned below.

Temp Fix:

1. Uninstall eva-decord (0.6.1)
2. Use python 3.8.* (as decord doesn't support python >= 3.9)
3. Install decord (0.6.0)

### Environment

- EvaDB: v0.3.0
- Eva-Decord: v0.6.1
- OS: Mac OS 10.15.7 on Intel based Mac

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by gaurav274** [comment]
@AmritK10 Is this still an issue?

**Comment by AmritK10** [comment]
Hey, this PR on eva-decord contains the fix: https://github.com/georgia-tech-db/eva-decord/pull/4
I had validated the changes on both intel and apple silicon Macs

**Comment by xzdandy** [comment]
What is the status of this PR? What is the next step? Thanks!

**Comment by AmritK10** [comment]
I believe it should be ready to be merged

**Comment by xzdandy** [comment]
Close this PR given it does not include change to the EvaDB repo. We can follow up in https://github.com/georgia-tech-db/eva-decord/pull/4. Thanks!
