### ISSUE TITLE
ClickHouse Integration

### ISSUE THREAD

**Issue by gaurav274** [georgia-tech-db/evadb#955]
### Search before asking

- [X] I have searched the EvaDB [issues](https://github.com/georgia-tech-db/eva/issues) and found no similar feature requests.

### Description

Similar to Postgres, add support for more databases.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by hershd23** [comment]
Hey I'll pick this issue

**Comment by xzdandy** [comment]
Hi, I think [Preethi1609](https://github.com/Preethi1609) is also working on the integration #1072

**Comment by hershd23** [comment]
Oh okay @Preethi1609 let me know if you are working on this. In that case I'll look for something else

**Comment by xzdandy** [comment]
We have introduced clickhouse integration in #1282.
