### ISSUE TITLE
xgboost Integration

### ISSUE THREAD

**Issue by gaurav274** [georgia-tech-db/evadb#961]
### Search before asking

- [X] I have searched the EvaDB [issues](https://github.com/georgia-tech-db/eva/issues) and found no similar feature requests.

### Description

Expand our integrations with ML libraries

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by jineetd** [comment]
We shall use Flaml Auto ML models for this purpose. The reasons for this are:
1. It is supported on Mac.
2. Microsoft maintains it, so it shall have a long time support.
