### ISSUE TITLE
Poor Error message if the engine does not exist while trying USE command

### ISSUE THREAD

**Issue by gaurav274** [georgia-tech-db/evadb#992]
### Search before asking

- [X] I have searched the EvaDB [issues](https://github.com/georgia-tech-db/eva/issues) and found no similar bug report.

### Bug

Current Message:
`NoneType object has no attribute engine `

Expected: Some better messaging and suggestions of what needs to be done. Like please run the create database command etc. 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by hershd23** [comment]
Hi can I take this? Looking for some starter issues to get up and running with EvaDB

**Comment by jiashenC** [comment]
> Hi can I take this? Looking for some starter issues to get up and running with EvaDB

@hershd23 Thanks for your interest. I am already working on this. Feel free to assign yourself to other issues.

**Comment by hershd23** [comment]
Sure thanks for your reply
