### ISSUE TITLE
Native query fails if there is a semicolon 

### ISSUE THREAD

**Issue by gaurav274** [georgia-tech-db/evadb#993]
### Search before asking

- [X] I have searched the EvaDB [issues](https://github.com/georgia-tech-db/eva/issues) and found no similar bug report.

### Bug

The following query fails. After removing the semicolon, it works as expected. If this is an expected behavior, we should document it. 
```
cursor.query("""
USE postgres_db {
  COPY airbnb_listing(id, name, summary, neighbourhood) FROM "listings.csv"
  DELIMITER "," CSV HEADER;}
""").df()
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by xzdandy** [comment]
The [documentation page](https://evadb.readthedocs.io/en/stable/source/reference/evaql/use.html) has been updated.
